# CAMBRIDGE LICENSES THE SOFTWARE "AS IS," AND MAKES NO EXPRESS OR IMPLIED WARRANTY OF ANY KIND. 
# CAMBRIDGE SPECIFICALLY DISCLAIMS ALL INDIRECT OR IMPLIED WARRANTIES TO THE FULL EXTENT ALLOWED BY APPLICABLE LAW,
# INCLUDING WITHOUT LIMITATION ALL IMPLIED WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, TITLE OR FITNESS FOR ANY PARTICULAR PURPOSE. 

# THE SOFTWARE IS DELIVERED IN ACCORDANCE WITH TERMS AND CONDITIONS SET OUT IN THE AGREED MEMORANDUM OF AGREEMENT (P5056-C-001 V1.0)
# AND THE SCHEDULE OF TECHNOLOGY WITH A RESTRICTIVE ENCUMBRANCE (P5056-M-005 V1.0). 


#!/bin/bash
cd python/gpt-lambda

ECR_URL=473723458256.dkr.ecr.eu-west-2.amazonaws.com
REPOSITORY_NAME=chalkbot-kampus-ecr
IMAGE_TAG=latest

aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin $ECR_URL
docker build -t chalkbot-ecr:latest .
docker tag chalkbot-ecr:latest "$ECR_URL/$REPOSITORY_NAME:$IMAGE_TAG"
docker push "$ECR_URL/$REPOSITORY_NAME:$IMAGE_TAG"